application: eka-lobby
version: 2
runtime: python27
instance_class: F4
api_version: 1
threadsafe: yes

# automatic_scaling:
#   max_idle_instances: 2
#   min_pending_latency: 5.0s

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

handlers:
- url: .*
  script: main.app
  secure: always
