application: eka-lobby
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: .*
  script: main.app
  secure: always
